name: preprocessing

on:
  push:
    branches:
      - main
      - master

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn kagglehub

    - name: Run Preprocessing Script
      run: |
        python preprocessing/automate_Shava.py

    - name: Commit and Push Preprocessed Data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add preprocessing/customer_preprocessed.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Automated: Update preprocessed data" && git push)
